# Dockerfile.hardhat
FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
# Instala Hardhat y otras dependencias de desarrollo
RUN npm install --save-dev hardhat

COPY . . # Copia el resto del proyecto

# No defines CMD o ENTRYPOINT aquí, ya que Docker Compose los sobrescribirá