# docker-compose.yml
version: '3.8'

services:
  # Servicio para el nodo de Hardhat
  hardhat_node:
    build:
      context: . # El contexto es el directorio actual (Bases)
      dockerfile: Dockerfile.hardhat # Usaremos un Dockerfile dedicado para Hardhat si es necesario, o el base
    image: hardhat_dev_env # Nombre de la imagen que creará Docker Compose
    ports:
      - "8545:8545" # Expone el puerto del nodo al host
    command: sh -c "npm install --save-dev hardhat && npx hardhat node --host 0.0.0.0" # Inicia el nodo

  # Servicio para el despliegue de Hardhat (temporal)
  hardhat_deploy:
    build:
      context: .
      dockerfile: Dockerfile.hardhat
    image: hardhat_dev_env # Reutilizamos la misma imagen
    command: sh -c "npm install --save-dev hardhat && npx hardhat run scripts/deploy.js --network hardhat_node" # Aquí está la clave
    depends_on:
      - hardhat_node # Asegura que el nodo esté corriendo antes de intentar desplegar
    # No exponemos puertos para el servicio de despliegue si solo es para ejecutar el script
    # volumes: # No es necesario si la imagen ya tiene el código, pero lo mantengo por si acaso necesitas npm install
    #   - .:/app # Monta el directorio actual del proyecto